---
build_from:
  aarch64: homeassistant/aarch64-addon-matter-server:8.5.0
  amd64: homeassistant/amd64-addon-matter-server:8.5.0
args:
  BASHIO_VERSION: 0.17.1
  TEMPIO_VERSION: 2024.11.2
  S6_OVERLAY_VERSION: 3.1.6.2
